Training Dataset Size: 1058
Test Dataset Size: 265
Traceback (most recent call last):
  File "/gpfs0/home1/gddaslab/rsjxw007/ABMNet/spatial_train_moments.py", line 25, in <module>
    model, device = SpatialModel.train_gat_moments(train_data, 45, n_inputs=data.n_inputs,n_outputs=data.n_outputs,n_rates=data.n_rates,
  File "/gpfs0/home1/gddaslab/rsjxw007/ABMNet/modules/utils/train.py", line 100, in train_gat_moments
    out = model(initial_graph.to(device), edges.to(device), rates.to(device))
  File "/home/gddaslab/rsjxw007/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/gpfs0/home1/gddaslab/rsjxw007/ABMNet/modules/models/spatial.py", line 85, in forward
    x = torch.cat((x, self.rates_encoder(rates).repeat(x.size()[0]).reshape((x.size()[0], x.size()[0]))), dim=1)
RuntimeError: shape '[10000, 10000]' is invalid for input of size 1280000
Job Statistics for 3765146:
           JobID       User               Start                 End    Elapsed     MaxRSS   TotalCPU      State Exit        NodeList                                  ReqTRES 
---------------- ---------- ------------------- ------------------- ---------- ---------- ---------- ---------- ---- --------------- ---------------------------------------- 
         3765146   rsjxw007 2023-05-31T12:30:41 2023-05-31T12:30:49   00:00:08             00:12.410     FAILED  1:0   r1pl-hpcf-g04 billing=16,cpu=16,gres/gpu=1,mem=119280+ 
   3765146.batch            2023-05-31T12:30:41 2023-05-31T12:30:49   00:00:08          0  00:12.406     FAILED  1:0   r1pl-hpcf-g04                                          
  3765146.extern            2023-05-31T12:30:41 2023-05-31T12:30:49   00:00:08          0  00:00.003  COMPLETED  0:0   r1pl-hpcf-g04                                          
CPU Efficiency: 9.38% of 00:02:08 core-walltime
